name: CI/CD

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Instal
        run: pnpm install
      - name: Lint
        run: pnpm check
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
